# Generated by: bin/compile lib/peg/built_in_rules.peg Peg::BuiltInRules -n Peg -o lib/peg/built_in_rules.rb
# Do not edit. Edit lib/peg/built_in_rules.peg instead.

require 'peg/grammar'
require 'peg/runtime'

class Peg::BuiltInRules < Peg::Grammar
  self.default_rule = :spaces
  self.rules = [:spaces, :space]

  def spaces
    Peg::ZeroOrMore.new(
      Peg::Apply.new(:space)
    )
  end

  def space
    Peg::CharSet.new(" \t\r\n")
  end
end
